// Upload Document Constants
export const UPLOAD_DOCUMENT_REQUEST = 'UPLOAD_DOCUMENT_REQUEST';
export const UPLOAD_DOCUMENT_SUCCESS = 'UPLOAD_DOCUMENT_SUCCESS';
export const UPLOAD_DOCUMENT_FAIL = 'UPLOAD_DOCUMENT_FAIL';
export const UPLOAD_DOCUMENT_RESET = 'UPLOAD_DOCUMENT_RESET';

// Get Uploads List Constants
export const GET_UPLOADS_REQUEST = 'GET_UPLOADS_REQUEST';
export const GET_UPLOADS_SUCCESS = 'GET_UPLOADS_SUCCESS';
export const GET_UPLOADS_FAIL = 'GET_UPLOADS_FAIL';
export const GET_UPLOADS_RESET = 'GET_UPLOADS_RESET';

// Get Upload Details Constants
export const GET_UPLOAD_DETAILS_REQUEST = 'GET_UPLOAD_DETAILS_REQUEST';
export const GET_UPLOAD_DETAILS_SUCCESS = 'GET_UPLOAD_DETAILS_SUCCESS';
export const GET_UPLOAD_DETAILS_FAIL = 'GET_UPLOAD_DETAILS_FAIL';
export const GET_UPLOAD_DETAILS_RESET = 'GET_UPLOAD_DETAILS_RESET';

// Update Upload Constants
export const UPDATE_UPLOAD_REQUEST = 'UPDATE_UPLOAD_REQUEST';
export const UPDATE_UPLOAD_SUCCESS = 'UPDATE_UPLOAD_SUCCESS';
export const UPDATE_UPLOAD_FAIL = 'UPDATE_UPLOAD_FAIL';
export const UPDATE_UPLOAD_RESET = 'UPDATE_UPLOAD_RESET';

// Delete Upload Constants
export const DELETE_UPLOAD_REQUEST = 'DELETE_UPLOAD_REQUEST';
export const DELETE_UPLOAD_SUCCESS = 'DELETE_UPLOAD_SUCCESS';
export const DELETE_UPLOAD_FAIL = 'DELETE_UPLOAD_FAIL';
export const DELETE_UPLOAD_RESET = 'DELETE_UPLOAD_RESET';

// Assign Signer Constants
export const ASSIGN_SIGNER_REQUEST = 'ASSIGN_SIGNER_REQUEST';
export const ASSIGN_SIGNER_SUCCESS = 'ASSIGN_SIGNER_SUCCESS';
export const ASSIGN_SIGNER_FAIL = 'ASSIGN_SIGNER_FAIL';
export const ASSIGN_SIGNER_RESET = 'ASSIGN_SIGNER_RESET';

// Sign Document Constants
export const SIGN_DOCUMENT_REQUEST = 'SIGN_DOCUMENT_REQUEST';
export const SIGN_DOCUMENT_SUCCESS = 'SIGN_DOCUMENT_SUCCESS';
export const SIGN_DOCUMENT_FAIL = 'SIGN_DOCUMENT_FAIL';
export const SIGN_DOCUMENT_RESET = 'SIGN_DOCUMENT_RESET';

// Get Pending Signatures Constants (for signers)
export const GET_PENDING_SIGNATURES_REQUEST = 'GET_PENDING_SIGNATURES_REQUEST';
export const GET_PENDING_SIGNATURES_SUCCESS = 'GET_PENDING_SIGNATURES_SUCCESS';
export const GET_PENDING_SIGNATURES_FAIL = 'GET_PENDING_SIGNATURES_FAIL';
export const GET_PENDING_SIGNATURES_RESET = 'GET_PENDING_SIGNATURES_RESET';

// Get Signed Documents Constants
export const GET_SIGNED_DOCUMENTS_REQUEST = 'GET_SIGNED_DOCUMENTS_REQUEST';
export const GET_SIGNED_DOCUMENTS_SUCCESS = 'GET_SIGNED_DOCUMENTS_SUCCESS';
export const GET_SIGNED_DOCUMENTS_FAIL = 'GET_SIGNED_DOCUMENTS_FAIL';
export const GET_SIGNED_DOCUMENTS_RESET = 'GET_SIGNED_DOCUMENTS_RESET';

// Upload Progress Constants
export const UPLOAD_PROGRESS_UPDATE = 'UPLOAD_PROGRESS_UPDATE';
export const UPLOAD_PROGRESS_RESET = 'UPLOAD_PROGRESS_RESET';

// Get Documents by Uploader ID Constants
export const GET_UPLOADER_DOCUMENTS_REQUEST = 'GET_UPLOADER_DOCUMENTS_REQUEST';
export const GET_UPLOADER_DOCUMENTS_SUCCESS = 'GET_UPLOADER_DOCUMENTS_SUCCESS';
export const GET_UPLOADER_DOCUMENTS_FAIL = 'GET_UPLOADER_DOCUMENTS_FAIL';
export const GET_UPLOADER_DOCUMENTS_RESET = 'GET_UPLOADER_DOCUMENTS_RESET';

// Get Documents by Signer ID Constants
export const GET_SIGNER_DOCUMENTS_REQUEST = 'GET_SIGNER_DOCUMENTS_REQUEST';
export const GET_SIGNER_DOCUMENTS_SUCCESS = 'GET_SIGNER_DOCUMENTS_SUCCESS';
export const GET_SIGNER_DOCUMENTS_FAIL = 'GET_SIGNER_DOCUMENTS_FAIL';
export const GET_SIGNER_DOCUMENTS_RESET = 'GET_SIGNER_DOCUMENTS_RESET';
